### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by JakeChampion** [dfcreative/weakset#1]
On NPM (and in [`package.json`](https://github.com/dfcreative/weakset/blob/master/package.json#L33)) it shows that the module is MIT licensed, on Github it shows it is Unlicensed licensed.

I was wondering if you could you clarify which one it is and update whichever version is incorrect?

**Comment by dy** [comment]
@JakeChampion thank you! Fixed by 3de2159968d4856f674c0ba14529764ae6e0654f
